Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA001','Guevara Xiomara');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA002','Parache Daiana');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA003','Rodriguez Marcela');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA004','Herrera Daiana');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA005','Preiti Antonella');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA006','Siles Vera Gonzalo');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA007','Añorga Nerina');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA008','Lapalma Camila');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA009','Francoso Francielle');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA010','Martinez Carla');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA011','Ricardinni Anabella');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA012','Caporale Natalia');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA013','Alvarez Eugenia');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA014','Encina Sofía');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA015','Fernandez Cielo');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA016','Pinto Carolina');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA017','Colli Paula');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA018','Chanquia Braian');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA019','Seoane Pablo');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA020','Roman Carina');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA021','Serruya Jimena');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA022','Dominguez Lucia');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA023','Vera Andrea');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA024','Pietrafesa Marcelo');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA025','Espada Mariana');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA026','Delgado Paola');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA027','Sosa Noelia');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA028','Ferreira Milena');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA029','Martín Pablo');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA030','Catanzano Camila');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA031','Sanchez Camila');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA032','Robledo Yanina');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA033','Caffieri Marcelo');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA034','Romero Yansan');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GSA035','Balassanian Mariana');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER001','OPERADOR_1');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER002','OPERADOR_2');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER003','OPERADOR_3');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER004','OPERADOR_4');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER005','OPERADOR_5');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER006','OPERADOR_6');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER007','OPERADOR_7');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER008','OPERADOR_8');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER009','OPERADOR_9');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER010','OPERADOR_10');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER011','OPERADOR_11');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER012','OPERADOR_12');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER013','OPERADOR_13');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER014','OPERADOR_14');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER015','OPERADOR_15');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER016','OPERADOR_16');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER017','OPERADOR_17');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER018','OPERADOR_18');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER019','OPERADOR_19');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER020','OPERADOR_20');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER021','OPERADOR_21');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER022','OPERADOR_22');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER023','OPERADOR_23');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER024','OPERADOR_24');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER025','OPERADOR_25');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER026','OPERADOR_26');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER027','OPERADOR_27');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER028','OPERADOR_28');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER029','OPERADOR_29');
Insert into USUARIOS(CODIGO,NOMBRE) values ('OPER030','OPERADOR_30');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR031','Russo, Roxana Fernanda');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR032','Benitez, Sara Soraya');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR033','Balan Castillo, Rosmery Josefina');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR034','Debora Degleve');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR035','Spiteri, Natalia Soledad');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR036','Spinelli, Fabiana Alejandra');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR037','Chiarante, Carolina');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR038','Caraballo, Flavia');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR039','Millares, Magdalena Victoria');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR040','Caseres, Clara Giselle');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR041','Paola Carbajal');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR042','Peña Sanchez María Betania');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR043','Herrera Maria Florencia');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR044','Goicoechea Mariela Soledad');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR045','Mallo Carolina Lorena');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR046','Maza Rodriguez Alejandro Antonio');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR047','Vizgarra Muriel Rocio');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR048','Nina Berdichevsky');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR049','Pablo Suarez');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR050','Araoz Joaquin');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR051','Tulchinsky Brenda Sara');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR052','Perkes Melanie');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR053','Jardin Bencomo Isabel Cristina');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR054','Rey Marisa Gabriela');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR055','Artaza Bruno Emiliano');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR056','Jordan Barbara Daniela');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR057','Machuca Monsalve Beytzy Carolina');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR058','Coronel Yanina Mariana');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR059','Zapata, Doraly');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR060','Quinteros Yamila Constanza');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR061','Saralegui Melina Abigail');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR062','Arcos, Jessica');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR063','Lecumberry, Javier Matias');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR064','Renus, Maria Alejandra');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR065','Giusti , Raul Omar');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR066','Cardozo , Melisa Victoria');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR067','Monzon, Patricia Alejandra');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR068','Castillo Marin, Angela Astrid');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR069','Migliorisi, Silvana Nora');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR070','Kaddarian, Carlos');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR071','Marinaro Magali Jazmin');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR072','Archaga María Cecilia');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR073','Esquivel Liza Sabina');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR074','Filippelli Daira Solange');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR075','Valenzuela Norciglia Juan Martin');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR076','Lugo Deborah Natali');
Insert into USUARIOS(CODIGO,NOMBRE) values ('GAR077','Nicola Valeria Anabel');
Insert into USUARIOS(CODIGO,NOMBRE) values ('3497','RE, SABRINA');
Insert into USUARIOS(CODIGO,NOMBRE) values ('7393','TORRES, NANCY');
Insert into USUARIOS(CODIGO,NOMBRE) values ('3990','VALDIVIESO, FACUNDO');
Insert into USUARIOS(CODIGO,NOMBRE) values ('3321','PONCE, EVELINE');
Insert into USUARIOS(CODIGO,NOMBRE) values ('7449','PORCEL, ROCIO');
Insert into USUARIOS(CODIGO,NOMBRE) values ('5908','DORADO, SILVIA');
Insert into USUARIOS(CODIGO,NOMBRE) values ('10168','SALVATIERRA, RICARDO');
Insert into USUARIOS(CODIGO,NOMBRE) values ('7571','RODRIGUEZ, ANALIA');
Insert into USUARIOS(CODIGO,NOMBRE) values ('7467','MACAYA, LILIANA');
Insert into USUARIOS(CODIGO,NOMBRE) values ('7383','RETTA, GIMENA');
Insert into USUARIOS(CODIGO,NOMBRE) values ('2005','DOMINGUEZ, PAOLA');
Insert into USUARIOS(CODIGO,NOMBRE) values ('6677','PEREZ, CLAUDIA');
Insert into USUARIOS(CODIGO,NOMBRE) values ('5368','ROBLEDO, LAURA');
Insert into USUARIOS(CODIGO,NOMBRE) values ('8712','ROJAS, MARIA FLAVIA');
Insert into USUARIOS(CODIGO,NOMBRE) values ('5302','MANNO, KARINA');
Insert into USUARIOS(CODIGO,NOMBRE) values ('8265','BRIGNARDELO, GABRIELA');
Insert into USUARIOS(CODIGO,NOMBRE) values ('8280','ROJAS, ROMINA');
Insert into USUARIOS(CODIGO,NOMBRE) values ('6492','BENEGAS, MIRIAM');
Insert into USUARIOS(CODIGO,NOMBRE) values ('3075','Soledad Jordan');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG001','Usuario  1');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG002','Usuario  2');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG003','Usuario  3');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG004','Usuario  4');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG005','Usuario  5');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG006','Usuario  6');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG007','Usuario  7');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG008','Usuario  8');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG009','Usuario  9');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG010','Usuario  10');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG011','Usuario  11');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG012','Usuario  12');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG013','Usuario  13');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG014','Usuario  14');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG015','Usuario  15');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG016','Usuario  16');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG017','Usuario  17');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG018','Usuario  18');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG019','Usuario  19');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG020','Usuario  20');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG021','Usuario  21');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG022','Usuario  22');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG023','Usuario  23');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG024','Usuario  24');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG025','Usuario  25');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG026','Usuario  26');
Insert into USUARIOS(CODIGO,NOMBRE) values ('ARG027','Usuario  27');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPCS01','');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPCS02','');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPCS03','');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPCS04','');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPCS05','');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPCS06','');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPCS07','');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC301','Usuario 301');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC302','Usuario 302');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC303','Usuario 303');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC304','Usuario 304');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC305','Usuario 305');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC306','Usuario 306');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC307','Usuario 307');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC308','Usuario 308');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC309','Usuario 309');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC310','Usuario 310');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC311','Usuario 311');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC312','Usuario 312');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC313','Usuario 313');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC314','Usuario 314');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC315','Usuario 315');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC316','Usuario 316');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC317','Usuario 317');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC318','Usuario 318');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC319','Usuario 319');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC320','Usuario 320');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC321','Usuario 321');
Insert into USUARIOS(CODIGO,NOMBRE) values ('WPC322','Usuario 322');
