/*blanqueo las passwords nuevas*/
UPDATE USUARIOS SET PASSWORD=SHA1(UPPER(CODIGO)) WHERE PASSWORD='';

/*crea sucursales en espejo*/
UPDATE USUARIOPERFILES_TMP SET VETRAMOCOMPLETO=1 WHERE  TOPE=1;

/*agrego supervisores*/
/*Puede dar cero registros actualizados.*/
INSERT INTO SUPERVISORUSUARIOS SELECT (SELECT IDUSUARIO FROM USUARIOS WHERE codigo='SUPGAR'),IDUSUARIO,1 FROM USUARIOS WHERE CODIGO LIKE 'GAR%' AND IDUSUARIO NOT IN (SELECT IDUSUARIO FROM SUPERVISORUSUARIOS);

INSERT INTO SUPERVISORUSUARIOS SELECT (SELECT IDUSUARIO FROM USUARIOS WHERE codigo='ARGSUP'),IDUSUARIO,1 FROM USUARIOS WHERE CODIGO LIKE 'ARG%' AND IDUSUARIO NOT IN (SELECT IDUSUARIO FROM SUPERVISORUSUARIOS);

INSERT INTO SUPERVISORUSUARIOS SELECT (SELECT IDUSUARIO FROM USUARIOS WHERE codigo='SUPwpc'),IDUSUARIO,1 FROM USUARIOS WHERE CODIGO LIKE 'WPC%' AND IDUSUARIO NOT IN (SELECT IDUSUARIO FROM SUPERVISORUSUARIOS);
