update USUARIOS set NOMBRE='Guevara Xiomara'    where CODIGO='GSA001';
update USUARIOS set NOMBRE='Parache Daiana'    where CODIGO='GSA002';
update USUARIOS set NOMBRE='Rodriguez Marcela'    where CODIGO='GSA003';
update USUARIOS set NOMBRE='Herrera Daiana'    where CODIGO='GSA004';
update USUARIOS set NOMBRE='Preiti Antonella'    where CODIGO='GSA005';
update USUARIOS set NOMBRE='Siles Vera Gonzalo'    where CODIGO='GSA006';
update USUARIOS set NOMBRE='Añorga Nerina'    where CODIGO='GSA007';
update USUARIOS set NOMBRE='Lapalma Camila'    where CODIGO='GSA008';
update USUARIOS set NOMBRE='Francoso Francielle'    where CODIGO='GSA009';
update USUARIOS set NOMBRE='Martinez Carla'    where CODIGO='GSA010';
update USUARIOS set NOMBRE='Ricardinni Anabella'    where CODIGO='GSA011';
update USUARIOS set NOMBRE='Caporale Natalia'    where CODIGO='GSA012';
update USUARIOS set NOMBRE='Alvarez Eugenia'    where CODIGO='GSA013';
update USUARIOS set NOMBRE='Encina Sofía'    where CODIGO='GSA014';
update USUARIOS set NOMBRE='Fernandez Cielo'    where CODIGO='GSA015';
update USUARIOS set NOMBRE='Pinto Carolina'    where CODIGO='GSA016';
update USUARIOS set NOMBRE='Colli Paula'    where CODIGO='GSA017';
update USUARIOS set NOMBRE='Chanquia Braian'    where CODIGO='GSA018';
update USUARIOS set NOMBRE='Seoane Pablo'    where CODIGO='GSA019';
update USUARIOS set NOMBRE='Roman Carina'    where CODIGO='GSA020';
update USUARIOS set NOMBRE='Serruya Jimena'    where CODIGO='GSA021';
update USUARIOS set NOMBRE='Dominguez Lucia'    where CODIGO='GSA022';
update USUARIOS set NOMBRE='Vera Andrea'    where CODIGO='GSA023';
update USUARIOS set NOMBRE='Pietrafesa Marcelo'    where CODIGO='GSA024';
update USUARIOS set NOMBRE='Espada Mariana'    where CODIGO='GSA025';
update USUARIOS set NOMBRE='Delgado Paola'    where CODIGO='GSA026';
update USUARIOS set NOMBRE='Sosa Noelia'    where CODIGO='GSA027';
update USUARIOS set NOMBRE='Ferreira Milena'    where CODIGO='GSA028';
update USUARIOS set NOMBRE='Martín Pablo'    where CODIGO='GSA029';
update USUARIOS set NOMBRE='Catanzano Camila'    where CODIGO='GSA030';
update USUARIOS set NOMBRE='Sanchez Camila'    where CODIGO='GSA031';
update USUARIOS set NOMBRE='Robledo Yanina'    where CODIGO='GSA032';
update USUARIOS set NOMBRE='Caffieri Marcelo'    where CODIGO='GSA033';
update USUARIOS set NOMBRE='Romero Yansan'    where CODIGO='GSA034';
update USUARIOS set NOMBRE='Balassanian Mariana'    where CODIGO='GSA035';
update USUARIOS set NOMBRE='OPERADOR_1'    where CODIGO='OPER001';
update USUARIOS set NOMBRE='OPERADOR_2'    where CODIGO='OPER002';
update USUARIOS set NOMBRE='OPERADOR_3'    where CODIGO='OPER003';
update USUARIOS set NOMBRE='OPERADOR_4'    where CODIGO='OPER004';
update USUARIOS set NOMBRE='OPERADOR_5'    where CODIGO='OPER005';
update USUARIOS set NOMBRE='OPERADOR_6'    where CODIGO='OPER006';
update USUARIOS set NOMBRE='OPERADOR_7'    where CODIGO='OPER007';
update USUARIOS set NOMBRE='OPERADOR_8'    where CODIGO='OPER008';
update USUARIOS set NOMBRE='OPERADOR_9'    where CODIGO='OPER009';
update USUARIOS set NOMBRE='OPERADOR_10'    where CODIGO='OPER010';
update USUARIOS set NOMBRE='OPERADOR_11'    where CODIGO='OPER011';
update USUARIOS set NOMBRE='OPERADOR_12'    where CODIGO='OPER012';
update USUARIOS set NOMBRE='OPERADOR_13'    where CODIGO='OPER013';
update USUARIOS set NOMBRE='OPERADOR_14'    where CODIGO='OPER014';
update USUARIOS set NOMBRE='OPERADOR_15'    where CODIGO='OPER015';
update USUARIOS set NOMBRE='OPERADOR_16'    where CODIGO='OPER016';
update USUARIOS set NOMBRE='OPERADOR_17'    where CODIGO='OPER017';
update USUARIOS set NOMBRE='OPERADOR_18'    where CODIGO='OPER018';
update USUARIOS set NOMBRE='OPERADOR_19'    where CODIGO='OPER019';
update USUARIOS set NOMBRE='OPERADOR_20'    where CODIGO='OPER020';
update USUARIOS set NOMBRE='OPERADOR_21'    where CODIGO='OPER021';
update USUARIOS set NOMBRE='OPERADOR_22'    where CODIGO='OPER022';
update USUARIOS set NOMBRE='OPERADOR_23'    where CODIGO='OPER023';
update USUARIOS set NOMBRE='OPERADOR_24'    where CODIGO='OPER024';
update USUARIOS set NOMBRE='OPERADOR_25'    where CODIGO='OPER025';
update USUARIOS set NOMBRE='OPERADOR_26'    where CODIGO='OPER026';
update USUARIOS set NOMBRE='OPERADOR_27'    where CODIGO='OPER027';
update USUARIOS set NOMBRE='OPERADOR_28'    where CODIGO='OPER028';
update USUARIOS set NOMBRE='OPERADOR_29'    where CODIGO='OPER029';
update USUARIOS set NOMBRE='OPERADOR_30'    where CODIGO='OPER030';
update USUARIOS set NOMBRE='Russo, Roxana Fernanda'    where CODIGO='GAR031';
update USUARIOS set NOMBRE='Benitez, Sara Soraya'    where CODIGO='GAR032';
update USUARIOS set NOMBRE='Balan Castillo, Rosmery Josefina'    where CODIGO='GAR033';
update USUARIOS set NOMBRE='Debora Degleve'    where CODIGO='GAR034';
update USUARIOS set NOMBRE='Spiteri, Natalia Soledad'    where CODIGO='GAR035';
update USUARIOS set NOMBRE='Spinelli, Fabiana Alejandra'    where CODIGO='GAR036';
update USUARIOS set NOMBRE='Chiarante, Carolina'    where CODIGO='GAR037';
update USUARIOS set NOMBRE='Caraballo, Flavia'    where CODIGO='GAR038';
update USUARIOS set NOMBRE='Millares, Magdalena Victoria'    where CODIGO='GAR039';
update USUARIOS set NOMBRE='Caseres, Clara Giselle'    where CODIGO='GAR040';
update USUARIOS set NOMBRE='Paola Carbajal'    where CODIGO='GAR041';
update USUARIOS set NOMBRE='Peña Sanchez María Betania'    where CODIGO='GAR042';
update USUARIOS set NOMBRE='Herrera Maria Florencia'    where CODIGO='GAR043';
update USUARIOS set NOMBRE='Goicoechea Mariela Soledad'    where CODIGO='GAR044';
update USUARIOS set NOMBRE='Mallo Carolina Lorena'    where CODIGO='GAR045';
update USUARIOS set NOMBRE='Maza Rodriguez Alejandro Antonio'    where CODIGO='GAR046';
update USUARIOS set NOMBRE='Vizgarra Muriel Rocio'    where CODIGO='GAR047';
update USUARIOS set NOMBRE='Nina Berdichevsky'    where CODIGO='GAR048';
update USUARIOS set NOMBRE='Pablo Suarez'    where CODIGO='GAR049';
update USUARIOS set NOMBRE='Araoz Joaquin'    where CODIGO='GAR050';
update USUARIOS set NOMBRE='Tulchinsky Brenda Sara'    where CODIGO='GAR051';
update USUARIOS set NOMBRE='Perkes Melanie'    where CODIGO='GAR052';
update USUARIOS set NOMBRE='Jardin Bencomo Isabel Cristina'    where CODIGO='GAR053';
update USUARIOS set NOMBRE='Rey Marisa Gabriela'    where CODIGO='GAR054';
update USUARIOS set NOMBRE='Artaza Bruno Emiliano'    where CODIGO='GAR055';
update USUARIOS set NOMBRE='Jordan Barbara Daniela'    where CODIGO='GAR056';
update USUARIOS set NOMBRE='Machuca Monsalve Beytzy Carolina'    where CODIGO='GAR057';
update USUARIOS set NOMBRE='Coronel Yanina Mariana'    where CODIGO='GAR058';
update USUARIOS set NOMBRE='Zapata, Doraly'    where CODIGO='GAR059';
update USUARIOS set NOMBRE='Quinteros Yamila Constanza'    where CODIGO='GAR060';
update USUARIOS set NOMBRE='Saralegui Melina Abigail'    where CODIGO='GAR061';
update USUARIOS set NOMBRE='Arcos, Jessica'    where CODIGO='GAR062';
update USUARIOS set NOMBRE='Lecumberry, Javier Matias'    where CODIGO='GAR063';
update USUARIOS set NOMBRE='Renus, Maria Alejandra'    where CODIGO='GAR064';
update USUARIOS set NOMBRE='Giusti , Raul Omar'    where CODIGO='GAR065';
update USUARIOS set NOMBRE='Cardozo , Melisa Victoria'    where CODIGO='GAR066';
update USUARIOS set NOMBRE='Monzon, Patricia Alejandra'    where CODIGO='GAR067';
update USUARIOS set NOMBRE='Castillo Marin, Angela Astrid'    where CODIGO='GAR068';
update USUARIOS set NOMBRE='Migliorisi, Silvana Nora'    where CODIGO='GAR069';
update USUARIOS set NOMBRE='Kaddarian, Carlos'    where CODIGO='GAR070';
update USUARIOS set NOMBRE='Marinaro Magali Jazmin'    where CODIGO='GAR071';
update USUARIOS set NOMBRE='Archaga María Cecilia'    where CODIGO='GAR072';
update USUARIOS set NOMBRE='Esquivel Liza Sabina'    where CODIGO='GAR073';
update USUARIOS set NOMBRE='Filippelli Daira Solange'    where CODIGO='GAR074';
update USUARIOS set NOMBRE='Valenzuela Norciglia Juan Martin'    where CODIGO='GAR075';
update USUARIOS set NOMBRE='Lugo Deborah Natali'    where CODIGO='GAR076';
update USUARIOS set NOMBRE='Nicola Valeria Anabel'    where CODIGO='GAR077';
update USUARIOS set NOMBRE='RE, SABRINA'    where CODIGO='3497';
update USUARIOS set NOMBRE='TORRES, NANCY'    where CODIGO='7393';
update USUARIOS set NOMBRE='VALDIVIESO, FACUNDO'    where CODIGO='3990';
update USUARIOS set NOMBRE='PONCE, EVELINE'    where CODIGO='3321';
update USUARIOS set NOMBRE='PORCEL, ROCIO'    where CODIGO='7449';
update USUARIOS set NOMBRE='DORADO, SILVIA'    where CODIGO='5908';
update USUARIOS set NOMBRE='SALVATIERRA, RICARDO'    where CODIGO='10168';
update USUARIOS set NOMBRE='RODRIGUEZ, ANALIA'    where CODIGO='7571';
update USUARIOS set NOMBRE='MACAYA, LILIANA'    where CODIGO='7467';
update USUARIOS set NOMBRE='RETTA, GIMENA'    where CODIGO='7383';
update USUARIOS set NOMBRE='DOMINGUEZ, PAOLA'    where CODIGO='2005';
update USUARIOS set NOMBRE='PEREZ, CLAUDIA'    where CODIGO='6677';
update USUARIOS set NOMBRE='ROBLEDO, LAURA'    where CODIGO='5368';
update USUARIOS set NOMBRE='ROJAS, MARIA FLAVIA'    where CODIGO='8712';
update USUARIOS set NOMBRE='MANNO, KARINA'    where CODIGO='5302';
update USUARIOS set NOMBRE='BRIGNARDELO, GABRIELA'    where CODIGO='8265';
update USUARIOS set NOMBRE='ROJAS, ROMINA'    where CODIGO='8280';
update USUARIOS set NOMBRE='BENEGAS, MIRIAM'    where CODIGO='6492';
update USUARIOS set NOMBRE='Soledad Jordan'    where CODIGO='3075';
update USUARIOS set NOMBRE='Usuario  1'    where CODIGO='ARG001';
update USUARIOS set NOMBRE='Usuario  2'    where CODIGO='ARG002';
update USUARIOS set NOMBRE='Usuario  3'    where CODIGO='ARG003';
update USUARIOS set NOMBRE='Usuario  4'    where CODIGO='ARG004';
update USUARIOS set NOMBRE='Usuario  5'    where CODIGO='ARG005';
update USUARIOS set NOMBRE='Usuario  6'    where CODIGO='ARG006';
update USUARIOS set NOMBRE='Usuario  7'    where CODIGO='ARG007';
update USUARIOS set NOMBRE='Usuario  8'    where CODIGO='ARG008';
update USUARIOS set NOMBRE='Usuario  9'    where CODIGO='ARG009';
update USUARIOS set NOMBRE='Usuario  10'    where CODIGO='ARG010';
update USUARIOS set NOMBRE='Usuario  11'    where CODIGO='ARG011';
update USUARIOS set NOMBRE='Usuario  12'    where CODIGO='ARG012';
update USUARIOS set NOMBRE='Usuario  13'    where CODIGO='ARG013';
update USUARIOS set NOMBRE='Usuario  14'    where CODIGO='ARG014';
update USUARIOS set NOMBRE='Usuario  15'    where CODIGO='ARG015';
update USUARIOS set NOMBRE='Usuario  16'    where CODIGO='ARG016';
update USUARIOS set NOMBRE='Usuario  17'    where CODIGO='ARG017';
update USUARIOS set NOMBRE='Usuario  18'    where CODIGO='ARG018';
update USUARIOS set NOMBRE='Usuario  19'    where CODIGO='ARG019';
update USUARIOS set NOMBRE='Usuario  20'    where CODIGO='ARG020';
update USUARIOS set NOMBRE='Usuario  21'    where CODIGO='ARG021';
update USUARIOS set NOMBRE='Usuario  22'    where CODIGO='ARG022';
update USUARIOS set NOMBRE='Usuario  23'    where CODIGO='ARG023';
update USUARIOS set NOMBRE='Usuario  24'    where CODIGO='ARG024';
update USUARIOS set NOMBRE='Usuario  25'    where CODIGO='ARG025';
update USUARIOS set NOMBRE='Usuario  26'    where CODIGO='ARG026';
update USUARIOS set NOMBRE='Usuario  27'    where CODIGO='ARG027';
update USUARIOS set NOMBRE=''    where CODIGO='WPCS01';
update USUARIOS set NOMBRE=''    where CODIGO='WPCS02';
update USUARIOS set NOMBRE=''    where CODIGO='WPCS03';
update USUARIOS set NOMBRE=''    where CODIGO='WPCS04';
update USUARIOS set NOMBRE=''    where CODIGO='WPCS05';
update USUARIOS set NOMBRE=''    where CODIGO='WPCS06';
update USUARIOS set NOMBRE=''    where CODIGO='WPCS07';
update USUARIOS set NOMBRE='Usuario 301'    where CODIGO='WPC301';
update USUARIOS set NOMBRE='Usuario 302'    where CODIGO='WPC302';
update USUARIOS set NOMBRE='Usuario 303'    where CODIGO='WPC303';
update USUARIOS set NOMBRE='Usuario 304'    where CODIGO='WPC304';
update USUARIOS set NOMBRE='Usuario 305'    where CODIGO='WPC305';
update USUARIOS set NOMBRE='Usuario 306'    where CODIGO='WPC306';
update USUARIOS set NOMBRE='Usuario 307'    where CODIGO='WPC307';
update USUARIOS set NOMBRE='Usuario 308'    where CODIGO='WPC308';
update USUARIOS set NOMBRE='Usuario 309'    where CODIGO='WPC309';
update USUARIOS set NOMBRE='Usuario 310'    where CODIGO='WPC310';
update USUARIOS set NOMBRE='Usuario 311'    where CODIGO='WPC311';
update USUARIOS set NOMBRE='Usuario 312'    where CODIGO='WPC312';
update USUARIOS set NOMBRE='Usuario 313'    where CODIGO='WPC313';
update USUARIOS set NOMBRE='Usuario 314'    where CODIGO='WPC314';
update USUARIOS set NOMBRE='Usuario 315'    where CODIGO='WPC315';
update USUARIOS set NOMBRE='Usuario 316'    where CODIGO='WPC316';
update USUARIOS set NOMBRE='Usuario 317'    where CODIGO='WPC317';
update USUARIOS set NOMBRE='Usuario 318'    where CODIGO='WPC318';
update USUARIOS set NOMBRE='Usuario 319'    where CODIGO='WPC319';
update USUARIOS set NOMBRE='Usuario 320'    where CODIGO='WPC320';
update USUARIOS set NOMBRE='Usuario 321'    where CODIGO='WPC321';
update USUARIOS set NOMBRE='Usuario 322'    where CODIGO='WPC322';
