INSERT INTO CARTERA_Backup SELECT IDCARTERA,IDMOROSO,IDGARANTE,TIPOCARTERA,TIPOPROCESO,FECHAPROCESO,SUCURSAL,
NUMCREDITO,DOLARES,IMPORTE,FECHA,CUOTAS,ULTIMACUOTA,DIAS,SALDO,FRAVSAENZ,CUOTASATRASADAS,AUXNUEVO,CANTATRASADAS,
CATEGORIA,TIPOCREDITO,VENDEDOR,OBSERVACIONES,DEBEPAGARINT,FECVENCIMIENTO,SALDOBCO,TIPOTARJETA,SALDOPESOS,SALDODOLAR,
CANTIMP,FECHAAGENDA,FECHAALTA,FECHABAJA,ESTADO,DEBAUTO,now()
from CARTERA;