SELECT
GRUPO,
SUM(CANTIDADPENDIENTE) CANTIDADPENDIENTE,
ROUND(SUM(PENDIENTE)) PENDIENTE,
SUM(CANTIDADCANCELADO)CANTIDADCANCELADO,
ROUND(SUM(CANCELADO)) CANCELADO,
SUM(CANTIDADTOTAL)CANTIDADTOTAL,
ROUND(SUM(TOTAL)) TOTAL,
SUM(TOTALCARTERAPROP) TOTALCARTERA,
SUM(CANCELADO)/SUM(TOTAL)*100 RECUPERO,
SUM(PENDIENTE)/SUM(TOTALCARTERAPROP)*100 Eficiencia,
SUM(TOTAL)/SUM(TOTALCARTERAPROP)*100 EFICIENCIA_INICIAL
 FROM HSTREPORTE1_DIARIA WHERE PERIODO=CONCAT(MONTH(CURRENT_DATE()),YEAR(CURRENT_DATE()))
 GROUP BY GRUPO;