SELECT GRUPO,SUM(CANTIDADPENDIENTE)CANTIDADPENDIENTE,
SUM(PENDIENTE)PENDIENTE,
SUM(CANCELADO)CANCELADO,
SUM(TOTAL)TOTAL,
SUM(TOTALCARTERAPROP)TOTALCARTERAPROP,
SUM(PENDIENTE)/SUM(TOTALCARTERAPROP)*100 Eficiencia,
SUM(TOTAL)/SUM(TOTALCARTERAPROP)*100 EficienciaInicial
FROM INICIO
GROUP BY GRUPO
