SELECT
CODIGO,
GRUPO,
NOMBRE,
CANTIDADPENDIENTE,
ROUND(PENDIENTE) PENDIENTE,
CANTIDADCANCELADO,
ROUND(CANCELADO) CANCELADO,
ROUND(TOTAL) TOTAL,
TOTALCARTERAPROP,
CANCELADO/TOTAL*100 RECUPERO,
PENDIENTE/TOTALCARTERAPROP*100 Eficiencia,
TOTAL/TOTALCARTERAPROP*100 EFICIENCIA_INICIAL
 FROM HSTREPORTE1_DIARIA WHERE PERIODO=CONCAT(MONTH(CURRENT_DATE()),YEAR(CURRENT_DATE()));