insert into callcenter.HSTREPORTE1_DIARIA
(PERIODO,
IDUSUARIO,
CODIGO,
NOMBRE,
CANTIDADPENDIENTE,
PENDIENTE,
CANTIDADCANCELADO,
CANCELADO,
CANTIDADPROMESA,
PROMESA,
CantidadTotal,
TOTAL,
GRUPO,
TOTALCARTERAPROP)
select concat(MONTH(CURRENT_DATE()),YEAR(CURRENT_DATE())) PERIODO,
d.IDUSUARIO,
CODIGO,
NOMBRE,
sum(CANTIDADPENDIENTE)CANTIDADPENDIENTE,
sum(PENDIENTE)PENDIENTE,
sum(CANTIDADCANCELADO)CANTIDADCANCELADO,
sum(CANCELADO) CANCELADO,
sum(CANTIDADPROMESA)CANTIDADPROMESA,
sum(PROMESA) PROMESA,
sum(CANTIDADTOTAL)CANTIDADTOTAL,
sum(TOTAL)TOTAL,
d.GRUPO,
sum(TOTALCARTERAPROP)TOTALCARTERAPROP
 from (
select sum( TOTALCARTERAPROP)TOTALCARTERAPROP, sum( TOTALCARTERA)TOTALCARTERA,IDUSUARIO,GRPTRAMO  from(
select a.TOTAL,round(a.TOTAL/b.TOTAL*c.TOTALCARTERA*1000) TOTALCARTERAPROP,TOTALCARTERA*1000 TOTALCARTERA,a.IDUSUARIO,a.IDSUCURSAL,a.GRPTRAMO from 
(select sum(MONTO)TOTAL,IDUSUARIO,pe.GRPTRAMO,SUCURSAL IDSUCURSAL   from DISTRIBUCION di 
join PERFILES pe on di.IDPERFIL=pe.IDPERFIL
group by IDUSUARIO,pe.GRPTRAMO,SUCURSAL) a 
join (select sum(MONTO)TOTAL,SUCURSAL IDSUCURSAL ,pe.GRPTRAMO  from DISTRIBUCION di
join PERFILES pe on di.IDPERFIL=pe.IDPERFIL
 group by SUCURSAL,pe.GRPTRAMO) b  on b.IDSUCURSAL=a.IDSUCURSAL and a.GRPTRAMO=b.GRPTRAMO
join TOTALCARTERA c on a.IDSUCURSAL=c.IDSUCURSAL  order by a.IDSUCURSAL
) a group by IDUSUARIO,GRPTRAMO
) a  
join  (
select us.IDUSUARIO, us.CODIGO, trim(concat(Nombre,' ',Apellido)) NOMBRE,
sum(Case 
when(ca.FECHAPROCESO=maca.FECHAPROCESO ) then  
    1
else
    0
end) CANTIDADPENDIENTE,
sum(Case 
when(ca.FECHAPROCESO=maca.FECHAPROCESO ) then  
    di.MONTO
else
    0
end) PENDIENTE,
sum(Case 
when(ca.FECHAPROCESO<maca.FECHAPROCESO ) then  
    1
else
    0
end) CANTIDADCANCELADO,
sum(Case 
when(ca.FECHAPROCESO<maca.FECHAPROCESO ) then  
    di.MONTO
else
    0
end) CANCELADO,
sum(Case 
when ca.ESTADO=3 and (ca.FECHAPROCESO=maca.FECHAPROCESO ) then  
    1
else
    0
end) CANTIDADPROMESA,
sum(Case 
when ca.ESTADO=3 and (ca.FECHAPROCESO=maca.FECHAPROCESO ) then  
    di.MONTO 
else
    0
end) PROMESA,
count(*) CantidadTotal,
Sum(di.MONTO) TOTAL,
lower(gr.GRUPO) GRUPO,pedi.GRPTRAMO
from CARTERA ca
join (select max(FECHAPROCESO)FECHAPROCESO from CARTERA) maca on 1=1

join DISTRIBUCION di on ca.IDCARTERA=di.IDCARTERA and di.IDLOTE=1
join PERFILES pedi on di.IDPERFIL=pedi.IDPERFIL
join USUARIOS us on di.IDUSUARIO=us.IDUSUARIO 
join GRUPOS gr on di.IDGRUPO=gr.IDGRUPO
join SUCURSALES su on ca.SUCURSAL=su.SUCURSAL
left join USUARIOPERFILES upe on su.IDSUCURSAL=upe.IDSUCURSAL and upe.IDUSUARIO=di.IDUSUARIO 
group by us.IDUSUARIO, us.CODIGO,trim(concat(Nombre,' ',Apellido)),lower(gr.GRUPO),pedi.GRPTRAMO 
order by lower(gr.GRUPO),trim(concat(Nombre,' ',Apellido))
) d on a.IDUSUARIO=d.IDUSUARIO and d.GRPTRAMO=a.GRPTRAMO
group by d.GRUPO,CODIGO,NOMBRE;

