SELECT
SUCURSAL,DESCTIPO,
SUM(CANTIDADPENDIENTE) CANTIDADPENDIENTE,
ROUND(SUM(PENDIENTE)) PENDIENTE,
SUM(CANTIDADCANCELADO),
ROUND(SUM(CANCELADO)) CANCELADO,
ROUND(SUM(TOTAL)) TOTAL,
SUM(TOTALCARTERA) TOTALCARTERA,
SUM(CANCELADO)/SUM(TOTAL)*100 RECUPERO,
SUM(PENDIENTE)/SUM(TOTALCARTERA)*100 Eficiencia,
SUM(TOTAL)/SUM(TOTALCARTERA)*100 EFICIENCIA_INICIAL
 FROM HSTREPORTE2 WHERE PERIODO=CONCAT(MONTH(CURRENT_DATE()),YEAR(CURRENT_DATE()))
 GROUP BY SUCURSAL,DESCTIPO;
