INSERT INTO INICIO  SELECT d.GRUPO,CODIGO,NOMBRE,SUM(CANTIDADPENDIENTE)CANTIDADPENDIENTE,SUM(PENDIENTE)PENDIENTE,SUM(CANTIDADTOTAL)CANTIDADTOTAL,
SUM(CANTIDADCANCELADO)CANTIDADCANCELADO,SUM(CANCELADO) CANCELADO,SUM(CANTIDADPROMESA)CANTIDADPROMESA,SUM(PROMESA) PROMESA,
SUM(TOTAL)TOTAL,SUM(TOTALCARTERAPROP)TOTALCARTERAPROP,SUM(TOTALCARTERA)TOTALCARTERA,SUM(PENDIENTE)/SUM(TOTALCARTERAPROP)*100 EFICIENCIA FROM (
SELECT SUM( TOTALCARTERAPROP)TOTALCARTERAPROP, SUM( TOTALCARTERA)TOTALCARTERA,IDUSUARIO,GRPTRAMO  
FROM(
SELECT a.TOTAL,ROUND(a.TOTAL/b.TOTAL*c.TOTALCARTERA*1000) TOTALCARTERAPROP,TOTALCARTERA*1000 TOTALCARTERA,a.IDUSUARIO,a.IDSUCURSAL,a.GRPTRAMO FROM 
(SELECT SUM(MONTO)TOTAL,IDUSUARIO,pe.GRPTRAMO,SUCURSAL IDSUCURSAL   FROM DISTRIBUCION di 
JOIN PERFILES pe ON di.IDPERFIL=pe.IDPERFIL
GROUP BY IDUSUARIO,pe.GRPTRAMO,SUCURSAL
) a 
JOIN (SELECT SUM(MONTO)TOTAL,SUCURSAL IDSUCURSAL ,pe.GRPTRAMO  FROM DISTRIBUCION di
JOIN PERFILES pe ON di.IDPERFIL=pe.IDPERFIL
 GROUP BY SUCURSAL,pe.GRPTRAMO) b  ON b.IDSUCURSAL=a.IDSUCURSAL AND a.GRPTRAMO=b.GRPTRAMO
JOIN TOTALCARTERA c ON a.IDSUCURSAL=c.IDSUCURSAL  
ORDER BY a.IDSUCURSAL
) a GROUP BY IDUSUARIO,GRPTRAMO
) a  
JOIN  (
SELECT us.IDUSUARIO, us.CODIGO, TRIM(CONCAT(us.Nombre,' ',us.Apellido)) NOMBRE,
SUM(CASE 
WHEN(ca.FECHAPROCESO=maca.FECHAPROCESO AND pedi.IDPERFIL = pe.IDPERFIL) THEN  
    1
ELSE
    0
END) CANTIDADPENDIENTE,
SUM(CASE 
WHEN(ca.FECHAPROCESO=maca.FECHAPROCESO AND pedi.IDPERFIL = pe.IDPERFIL) THEN  
    di.MONTO
ELSE
    0
END) PENDIENTE,
SUM(CASE 
WHEN(ca.FECHAPROCESO<maca.FECHAPROCESO OR pedi.IDPERFIL <> pe.IDPERFIL) THEN  
    1
ELSE
    0
END) CANTIDADCANCELADO,
SUM(CASE 
WHEN(ca.FECHAPROCESO<maca.FECHAPROCESO OR pedi.IDPERFIL <> pe.IDPERFIL) THEN  
    di.MONTO
ELSE
    0
END) CANCELADO,
SUM(CASE 
WHEN ca.ESTADO=3 AND DATE(ca.FECHAAGENDA)>=ca.FECHAPROCESO AND (ca.FECHAPROCESO=maca.FECHAPROCESO AND pedi.IDPERFIL = pe.IDPERFIL) THEN  
    1
ELSE
    0
END) CANTIDADPROMESA,
SUM(CASE 
WHEN ca.ESTADO=3 AND DATE(ca.FECHAAGENDA)>=ca.FECHAPROCESO AND (ca.FECHAPROCESO=maca.FECHAPROCESO AND pedi.IDPERFIL = pe.IDPERFIL) THEN  
    di.MONTO 
ELSE
    0
END) PROMESA,
COUNT(*) CantidadTotal,
SUM(di.MONTO) TOTAL,
LOWER(gr.GRUPO) GRUPO,pedi.GRPTRAMO
FROM CARTERA ca
JOIN (SELECT MAX(FECHAPROCESO)FECHAPROCESO FROM CARTERA) maca ON 1=1
JOIN PERFILES pe ON ca.TIPOCARTERA=pe.TIPOCARTERA AND ca.TIPOPROCESO=pe.TIPOPROCESO
JOIN DISTRIBUCION di ON ca.IDCARTERA=di.IDCARTERA AND di.IDLOTE=1
JOIN PERFILES pedi ON di.IDPERFIL=pedi.IDPERFIL
JOIN USUARIOS us ON di.IDUSUARIO=us.IDUSUARIO
JOIN GRUPOS gr ON di.IDGRUPO=gr.IDGRUPO
JOIN SUCURSALES su ON ca.SUCURSAL=su.SUCURSAL
LEFT JOIN USUARIOPERFILES upe ON su.IDSUCURSAL=upe.IDSUCURSAL AND upe.IDUSUARIO=di.IDUSUARIO AND upe.IDPERFIL=pe.IDPERFIL
GROUP BY us.IDUSUARIO, us.CODIGO,TRIM(CONCAT(us.Nombre,' ',us.Apellido)),LOWER(gr.GRUPO),pedi.GRPTRAMO ORDER BY LOWER(gr.GRUPO),TRIM(CONCAT(us.Nombre,' ',us.Apellido))
) d ON a.IDUSUARIO=d.IDUSUARIO AND d.GRPTRAMO=a.GRPTRAMO
GROUP BY d.GRUPO,CODIGO,NOMBRE
